# Generated by Django 5.1.4 on 2026-05-10 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcentrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField()),
                ('average_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('min_score', models.FloatField()),
                ('gaze_stability_avg', models.FloatField(blank=True, null=True)),
                ('posture_score_avg', models.FloatField(blank=True, null=True)),
                ('face_direction_avg', models.FloatField(blank=True, null=True)),
                ('center_focus_avg', models.FloatField(blank=True, null=True)),
                ('score_records', models.JSONField(default=list)),
                ('focus_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concentration Log',
                'verbose_name_plural': 'Concentration Logs',
                'db_table': 'concentration_logs',
                'ordering': ['-record_date'],
            },
        ),
    ]
